//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DLProg.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DLProg.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic Configuration.
        /// </summary>
        public static string BasicConfiguration_BasicConfiguration {
            get {
                return ResourceManager.GetString("BasicConfiguration_BasicConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Up.
        /// </summary>
        public static string Browser_Up {
            get {
                return ResourceManager.GetString("Browser_Up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Configuration.
        /// </summary>
        public static string DownloadConfiguration_DownloadConfiguration {
            get {
                return ResourceManager.GetString("DownloadConfiguration_DownloadConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Errors_Error {
            get {
                return ResourceManager.GetString("Errors_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errors.
        /// </summary>
        public static string Errors_Errors {
            get {
                return ResourceManager.GetString("Errors_Errors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL.
        /// </summary>
        public static string Errors_URL {
            get {
                return ResourceManager.GetString("Errors_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a folder to place your downloaded files in..
        /// </summary>
        public static string FolderSelection_Description {
            get {
                return ResourceManager.GetString("FolderSelection_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log.
        /// </summary>
        public static string Log_Log {
            get {
                return ResourceManager.GetString("Log_Log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string Menu_New {
            get {
                return ResourceManager.GetString("Menu_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string Menu_Open {
            get {
                return ResourceManager.GetString("Menu_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string Menu_Options {
            get {
                return ResourceManager.GetString("Menu_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Menu_Save {
            get {
                return ResourceManager.GetString("Menu_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save as.
        /// </summary>
        public static string Menu_SaveAs {
            get {
                return ResourceManager.GetString("Menu_SaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New project....
        /// </summary>
        public static string NewDialog_Title {
            get {
                return ResourceManager.GetString("NewDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dlp.
        /// </summary>
        public static string OpenFileDialog_DefaultExt {
            get {
                return ResourceManager.GetString("OpenFileDialog_DefaultExt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DownloadProg project files (*.dlp)|*.dlp|All files (*.*)|*.*.
        /// </summary>
        public static string OpenFileDialog_Filter {
            get {
                return ResourceManager.GetString("OpenFileDialog_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a project file..
        /// </summary>
        public static string OpenFileDialog_Title {
            get {
                return ResourceManager.GetString("OpenFileDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filename.
        /// </summary>
        public static string Queue_Filename {
            get {
                return ResourceManager.GetString("Queue_Filename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queue.
        /// </summary>
        public static string Queue_Queue {
            get {
                return ResourceManager.GetString("Queue_Queue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL.
        /// </summary>
        public static string Queue_URL {
            get {
                return ResourceManager.GetString("Queue_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear errors.
        /// </summary>
        public static string Ribbon_ClearErrors {
            get {
                return ResourceManager.GetString("Ribbon_ClearErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear queue.
        /// </summary>
        public static string Ribbon_ClearQueue {
            get {
                return ResourceManager.GetString("Ribbon_ClearQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Ribbon_Home {
            get {
                return ResourceManager.GetString("Ribbon_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main.
        /// </summary>
        public static string Ribbon_Main {
            get {
                return ResourceManager.GetString("Ribbon_Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queue.
        /// </summary>
        public static string Ribbon_Queue {
            get {
                return ResourceManager.GetString("Ribbon_Queue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requeue errors.
        /// </summary>
        public static string Ribbon_RequeueErrors {
            get {
                return ResourceManager.GetString("Ribbon_RequeueErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string Ribbon_Start {
            get {
                return ResourceManager.GetString("Ribbon_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string Ribbon_Stop {
            get {
                return ResourceManager.GetString("Ribbon_Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dlp.
        /// </summary>
        public static string SaveFileDialog_DefaultExt {
            get {
                return ResourceManager.GetString("SaveFileDialog_DefaultExt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DownloadProg project files (*.dlp)|*.dlp|All files (*.*)|*.*.
        /// </summary>
        public static string SaveFileDialog_Filter {
            get {
                return ResourceManager.GetString("SaveFileDialog_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a file to save your project settings and state in..
        /// </summary>
        public static string SaveFileDialog_Title {
            get {
                return ResourceManager.GetString("SaveFileDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Script.
        /// </summary>
        public static string Script_Script {
            get {
                return ResourceManager.GetString("Script_Script", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max download speed:.
        /// </summary>
        public static string StatusBar_MaxDownloadSpeed {
            get {
                return ResourceManager.GetString("StatusBar_MaxDownloadSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current URL.
        /// </summary>
        public static string Workers_CurrentURL {
            get {
                return ResourceManager.GetString("Workers_CurrentURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloaded.
        /// </summary>
        public static string Workers_Downloaded {
            get {
                return ResourceManager.GetString("Workers_Downloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progress.
        /// </summary>
        public static string Workers_Progress {
            get {
                return ResourceManager.GetString("Workers_Progress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workers.
        /// </summary>
        public static string Workers_Workers {
            get {
                return ResourceManager.GetString("Workers_Workers", resourceCulture);
            }
        }
    }
}
